# Generated by Django 4.1.7 on 2023-02-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('occupied', models.BooleanField()),
                ('owner', models.CharField(max_length=255)),
                ('dateFrom', models.CharField(max_length=255)),
                ('nOfDays', models.IntegerField()),
            ],
        ),
    ]
